# Generated by Django 3.1.3 on 2020-11-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201119_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField(default=0)),
                ('email', models.CharField(default='', max_length=50)),
                ('sunject', models.CharField(default='', max_length=50)),
                ('message', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
