# Generated by Django 3.1.3 on 2020-11-25 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='sunject',
            new_name='subject',
        ),
    ]
