# Generated by Django 3.1.3 on 2020-11-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20201125_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('all_items', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField(default=0)),
                ('email', models.CharField(default='', max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(default='', max_length=10)),
                ('state', models.CharField(default='', max_length=10)),
                ('zip', models.IntegerField(default=0)),
            ],
        ),
    ]
