# Generated by Django 3.2 on 2022-11-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_category_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='shop.Product'),
        ),
    ]
