# Generated by Django 3.1.3 on 2020-11-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_tracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='order_id',
            field=models.IntegerField(default='0'),
        ),
    ]
